### ISSUE TITLE
observation model: non constant covariance

### ISSUE THREAD

**Issue by joansola** [artivis/kalmanif#1]
I have quickly checked out the se2 example. I wonder whether the obs models accept non-constant covariances, that is, something that allows the following update

```c++
ekf.update(gps_measurement_model, y_gps, R_gps);
```

**Comment by artivis** [comment]
The covariance is 'attached' to the `measurement_model` object, you can thus update the covariance value before calling the filter update, e.g.

```cpp
gps_measurement_model.setCovariance(R_gps);
ekf.update(gps_measurement_model, y_gps);
```

**Comment by joansola** [comment]
OK!
