### ISSUE TITLE
How long is the demo?

### ISSUE THREAD

**Issue by joansola** [artivis/kalmanif#2]
Running demo_se3 for a while... seems to never end!

Maybe add a time line t =t_current / t_final, just to the right of the `------` separation line

**Comment by joansola** [comment]
OK I was apparently on debug mode... muck quicker in release!

**Comment by artivis** [comment]
For future reference, one should compile in `Release` with `NDEBUG` to seriously speed up the execution, see e.g. the related [hint in the doc](https://github.com/artivis/kalmanif/blob/devel/CONTRIBUTING.md#running-examplestests).
