### ISSUE TITLE
Where are the plots of demo_se3?

### ISSUE THREAD

**Issue by joansola** [artivis/kalmanif#3]
Ran se3 with gnuplot installed and the correct build according to instructions. Where are the plots?

**Comment by joansola** [comment]
OK I was apparently on debug mode... muck quicker in release!

**Comment by artivis** [comment]
Are you passing the runtime-flags as well? See e.g. the [demo doc page](https://github.com/artivis/kalmanif/blob/devel/docs/demo.md) and specifically the [demo options](https://github.com/artivis/kalmanif/blob/devel/docs/demo.md#the-demo-options) section.
Or simply run `./demo_x --help`.

**Comment by joansola** [comment]
maaan! ok!

OK then , my bad... bu how about adding info on readme.md about all this demos documentation? at least a mention with a link
